export const PERMISSIONS = {
  ADMIN_ACCESS: "admin.access",
  ADMIN_USERS_READ: "admin.users.read",
  ADMIN_USERS_MANAGE: "admin.users.manage",
  ADMIN_AUDIT_READ: "admin.audit.read",
  CMS_PAGES_READ: "cms.pages.read",
  CMS_PAGES_MANAGE: "cms.pages.manage",
  CMS_PAGES_PUBLISH: "cms.pages.publish",
  CATALOG_CATEGORIES_READ: "catalog.categories.read",
  CATALOG_CATEGORIES_MANAGE: "catalog.categories.manage",
  CATALOG_PRODUCTS_READ: "catalog.products.read",
  CATALOG_PRODUCTS_MANAGE: "catalog.products.manage",
  CRM_CONTACTS_READ: "crm.contacts.read",
  CRM_CONTACTS_MANAGE: "crm.contacts.manage",
  CRM_COMPANIES_READ: "crm.companies.read",
  CRM_COMPANIES_MANAGE: "crm.companies.manage",
  CRM_DEALS_READ: "crm.deals.read",
  CRM_DEALS_MANAGE: "crm.deals.manage",
  CRM_ACTIVITIES_READ: "crm.activities.read",
  CRM_ACTIVITIES_MANAGE: "crm.activities.manage",
  DELIVERY_ORDERS_READ: "delivery.orders.read",
  DELIVERY_ORDERS_MANAGE: "delivery.orders.manage",
  DELIVERY_SCHEDULE_READ: "delivery.schedule.read",
  DELIVERY_SCHEDULE_MANAGE: "delivery.schedule.manage",
  FINANCE_INVOICES_READ: "finance.invoices.read",
  FINANCE_INVOICES_MANAGE: "finance.invoices.manage",
  FINANCE_PAYMENTS_READ: "finance.payments.read",
  FINANCE_PAYMENTS_MANAGE: "finance.payments.manage",
  INTEGRATIONS_READ: "integrations.read",
  INTEGRATIONS_MANAGE: "integrations.manage",
  WEBHOOKS_READ: "webhooks.read",
  WEBHOOKS_MANAGE: "webhooks.manage",
  CMS_MEDIA_READ: "cms.media.read",
  CMS_MEDIA_MANAGE: "cms.media.manage",
  SERVICE_CASES_READ: "service.cases.read",
  SERVICE_CASES_MANAGE: "service.cases.manage",
  CRM_LEADS_READ: "crm.leads.read",
  CRM_LEADS_MANAGE: "crm.leads.manage",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLES = {
  ADMINISTRATOR: "administrator",
} as const;

export type RoleCode = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSION_DEFINITIONS: ReadonlyArray<{
  code: PermissionCode;
  description: string;
}> = [
  { code: PERMISSIONS.ADMIN_ACCESS, description: "Access the administration panel" },
  { code: PERMISSIONS.ADMIN_USERS_READ, description: "View users and role assignments" },
  { code: PERMISSIONS.ADMIN_USERS_MANAGE, description: "Manage users and role assignments" },
  { code: PERMISSIONS.ADMIN_AUDIT_READ, description: "View audit records" },
  { code: PERMISSIONS.CMS_PAGES_READ, description: "View CMS pages" },
  { code: PERMISSIONS.CMS_PAGES_MANAGE, description: "Create and edit CMS pages" },
  { code: PERMISSIONS.CMS_PAGES_PUBLISH, description: "Publish CMS pages" },
  { code: PERMISSIONS.CATALOG_CATEGORIES_READ, description: "View catalogue categories" },
  { code: PERMISSIONS.CATALOG_CATEGORIES_MANAGE, description: "Create and edit catalogue categories" },
  { code: PERMISSIONS.CATALOG_PRODUCTS_READ, description: "View catalogue products" },
  { code: PERMISSIONS.CATALOG_PRODUCTS_MANAGE, description: "Create and edit catalogue products" },
  { code: PERMISSIONS.CRM_CONTACTS_READ, description: "View CRM contacts" },
  { code: PERMISSIONS.CRM_CONTACTS_MANAGE, description: "Create and edit CRM contacts" },
  { code: PERMISSIONS.CRM_COMPANIES_READ, description: "View CRM companies" },
  { code: PERMISSIONS.CRM_COMPANIES_MANAGE, description: "Create and edit CRM companies" },
  { code: PERMISSIONS.CRM_DEALS_READ, description: "View CRM deals" },
  { code: PERMISSIONS.CRM_DEALS_MANAGE, description: "Create and edit CRM deals" },
  { code: PERMISSIONS.CRM_ACTIVITIES_READ, description: "View CRM activities" },
  { code: PERMISSIONS.CRM_ACTIVITIES_MANAGE, description: "Create and edit CRM activities" },
  { code: PERMISSIONS.DELIVERY_ORDERS_READ, description: "View work orders" },
  { code: PERMISSIONS.DELIVERY_ORDERS_MANAGE, description: "Create and edit work orders" },
  { code: PERMISSIONS.DELIVERY_SCHEDULE_READ, description: "View schedules" },
  { code: PERMISSIONS.DELIVERY_SCHEDULE_MANAGE, description: "Create and edit schedules" },
  { code: PERMISSIONS.FINANCE_INVOICES_READ, description: "View invoices" },
  { code: PERMISSIONS.FINANCE_INVOICES_MANAGE, description: "Create and edit invoices" },
  { code: PERMISSIONS.FINANCE_PAYMENTS_READ, description: "View payments" },
  { code: PERMISSIONS.FINANCE_PAYMENTS_MANAGE, description: "Record and manage payments" },
  { code: PERMISSIONS.INTEGRATIONS_READ, description: "View integrations" },
  { code: PERMISSIONS.INTEGRATIONS_MANAGE, description: "Create and manage integrations" },
  { code: PERMISSIONS.WEBHOOKS_READ, description: "View webhooks" },
  { code: PERMISSIONS.WEBHOOKS_MANAGE, description: "Create and manage webhooks" },
  { code: PERMISSIONS.CMS_MEDIA_READ, description: "View uploaded media files" },
  { code: PERMISSIONS.CMS_MEDIA_MANAGE, description: "Upload and delete media files" },
  { code: PERMISSIONS.SERVICE_CASES_READ, description: "View service cases" },
  { code: PERMISSIONS.SERVICE_CASES_MANAGE, description: "Create and manage service cases" },
  { code: PERMISSIONS.CRM_LEADS_READ, description: "View CRM leads" },
  { code: PERMISSIONS.CRM_LEADS_MANAGE, description: "Create and manage CRM leads" },
];

export const ROLE_DEFINITIONS: ReadonlyArray<{
  code: RoleCode;
  description: string;
  name: string;
  permissions: PermissionCode[];
}> = [
  {
    code: ROLES.ADMINISTRATOR,
    description: "Full administration access for the 7ice platform",
    name: "Administrator",
    permissions: [
      PERMISSIONS.ADMIN_ACCESS,
      PERMISSIONS.ADMIN_USERS_READ,
      PERMISSIONS.ADMIN_USERS_MANAGE,
      PERMISSIONS.ADMIN_AUDIT_READ,
      PERMISSIONS.CMS_PAGES_READ,
      PERMISSIONS.CMS_PAGES_MANAGE,
      PERMISSIONS.CMS_PAGES_PUBLISH,
      PERMISSIONS.CATALOG_CATEGORIES_READ,
      PERMISSIONS.CATALOG_CATEGORIES_MANAGE,
      PERMISSIONS.CATALOG_PRODUCTS_READ,
      PERMISSIONS.CATALOG_PRODUCTS_MANAGE,
      PERMISSIONS.CRM_CONTACTS_READ,
      PERMISSIONS.CRM_CONTACTS_MANAGE,
      PERMISSIONS.CRM_COMPANIES_READ,
      PERMISSIONS.CRM_COMPANIES_MANAGE,
      PERMISSIONS.CRM_DEALS_READ,
      PERMISSIONS.CRM_DEALS_MANAGE,
      PERMISSIONS.CRM_ACTIVITIES_READ,
      PERMISSIONS.CRM_ACTIVITIES_MANAGE,
      PERMISSIONS.DELIVERY_ORDERS_READ,
      PERMISSIONS.DELIVERY_ORDERS_MANAGE,
      PERMISSIONS.DELIVERY_SCHEDULE_READ,
      PERMISSIONS.DELIVERY_SCHEDULE_MANAGE,
      PERMISSIONS.FINANCE_INVOICES_READ,
      PERMISSIONS.FINANCE_INVOICES_MANAGE,
      PERMISSIONS.FINANCE_PAYMENTS_READ,
      PERMISSIONS.FINANCE_PAYMENTS_MANAGE,
      PERMISSIONS.INTEGRATIONS_READ,
      PERMISSIONS.INTEGRATIONS_MANAGE,
      PERMISSIONS.WEBHOOKS_READ,
      PERMISSIONS.WEBHOOKS_MANAGE,
      PERMISSIONS.CMS_MEDIA_READ,
      PERMISSIONS.CMS_MEDIA_MANAGE,
      PERMISSIONS.SERVICE_CASES_READ,
      PERMISSIONS.SERVICE_CASES_MANAGE,
      PERMISSIONS.CRM_LEADS_READ,
      PERMISSIONS.CRM_LEADS_MANAGE,
    ],
  },
];
